@id=a92ec341-1768-4693-adf5-609b7b7cea2b

PUT http://localhost:5129/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Vegan Sunshine",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}